### ISSUE TITLE
How to call coroutines from consumer callback?

### ISSUE THREAD

**Issue by georgwaechter** [benjamin-hodgson/asynqp#11]
Hi,

I can't figure out how to call coroutines from my consumer callback. My first try was to mark my callback as a coroutine itself, but this does not work as the callbacks aren't called using "yield from".

My next approach was to use "asyncio.get_event_loop().run_until_complete()". Sadly this does not work either, it raises an "RuntimeError: Event loop is running.".

After reading many stuff related to asyncio, I conclude that it is not possible. I hope i'm wrong?

**Comment by georgwaechter** [comment]
An idea: What about checking whether the callback is a coroutine within queue.py/Consumers.deliver? If true, use "yield from", if not use "call_soon"?

**Comment by benjamin-hodgson** [comment]
`consume` expects a regular function as its callback, not a coroutine. So you should write a callback which schedules your coroutine with the event loop, using [`asyncio.async()`](https://docs.python.org/3/library/asyncio-task.html#asyncio.async).

```python
queue.consume(lambda msg: asyncio.async(my_coroutine(msg)))
```

`yield from` is not available within the `deliver` function because it is not called in the context of a coroutine stack.

I recently [answered](http://stackoverflow.com/questions/28293198/calling-a-remote-procedure-from-a-subscriber-and-resolving-the-asyncio-promise/28365674#28365674) a very similar Stack Overflow question.

**Comment by georgwaechter** [comment]
this is a nice solution. thanks for your great support!
