### ISSUE TITLE
Raise exception on lost connection

### ISSUE THREAD

**Issue by lenzenmi** [benjamin-hodgson/asynqp#15]
I've been playing with asynqp a little bit, and I'm really liking it.

I'm trying to figure out how to handle reconnecting in the case of a lost connection. With a producer I get the following output on the console, but I don't seem to be able to capture it in the loop error handler.
   
    socket.send() raised exception

With a consumer, no exception and no error are raised.

I tried creating an async task that would simply try to open a new channel with a timeout. If the timeout exception is raised, I assume the connection is down then try to restart a new connection. The problem in this case is that I can't seem to stop the old consuming task. Calling the .close() method on the connection or channel blocks forever when the connection is down, as does a call to .cancel() on the consumer.

Do you have any thoughts on how a lost connection can be detected, and consumers rebooted with the new connection?

Thanks for all the work you are doing on this.

**Comment by benjamin-hodgson** [comment]
I think there are a few related issues here:

1. When a TCP connection unexpectedly drops, there's no exception to notify application code of the error.
2. When the TCP connection has dropped, you can't manually `close` a connection.
3. When the TCP connection has dropped, you can't manually `close` a channel.
4. When the TCP connection has dropped, you can't unsubscribe existing consumers.

Regarding point 1. Error handling in async code is generally quite complicated (where should the exception go if all your application code is currently idle?). `asyncio` approaches the issue by allowing you to register an [exception handler](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.BaseEventLoop.set_exception_handler) with the event loop - so in theory all `asynqp` needs to do is raise an appropriate exception when the connection is lost, and then you can use the loop's exception handler to build any application-specific retry logic.

I happen to know that the transport calls [`Protocol.connection_lost`](https://docs.python.org/3/library/asyncio-protocol.html#asyncio.BaseProtocol.connection_lost) when the socket dies. It looks like [our `Protocol`](https://github.com/benjamin-hodgson/asynqp/blob/master/src/asynqp/protocol.py) doesn't override that method. I think all it needs to do is `raise ConnectionLost from exc` - I'll accept a pull request ([with tests](https://github.com/benjamin-hodgson/asynqp/blob/master/CONTRIBUTING.md)) which addresses that (I may get some time to work on it tomorrow but I can't make any promises).

Points 2-4 seem related to me (though I split them up because they may require separate fixes). Thinking out loud - I guess that those three methods try to send a frame over the wire to the server, which blocks forever because the socket is dead. I suppose one option would be to throw an exception when you try to send data through the protocol if the connection has been lost, and do some sort of "emergency shut-down" of any live objects or tasks which assume the connection is still open.

In general, `asynqp`'s error handling capabilities have room for improvement. Thanks very much for raising the issue :smiley: 

Sorry for the guesswork-filled reply, my brain has not been in AMQP mode for a while so the neural pathways have crusted up a bit :wink:

**Comment by lenzenmi** [comment]
I took a quick look through the code, and have a few thoughts I figured I'd bounce off of you.

1) I think raising a custom error and allowing the client to install a base error handler to handle a reconnection is the right approach. It seems to me that there are two places that should raise this error. The ```Protoco.connection_lost``` method as you mentioned, but also inside ```HeartbeatMonitor.heartbeat_timed_out()```

2) Things seem to block waiting on responses from the server inside of ```Syncroniser.await()```. It seems reasonable that if a connection is closed, there's no point in awaiting on anything so an exception should be set inside each future in each Syncroniser. The problem is that each connection needs to know about each Syncroniser in use in order to do that. I haven't totally digested how it's broken up, but I think the intial connection will have it's own Syncroniser, then each channel, and again each queue. I'm guessing that we would store a list inside each protocol instance and pass a reference to each channel/queue so that they can register any Syncronisers created with the connection. Then, when the heartbeats time out, or the connection_lost callback is triggered a set_exceptions method is called on each registered sycnroniser for that protocol instance(connection). Then each function that could be awaiting will have to look for the exception and handle it appropriately.

I'd be happy to try to put together a pull request with tests, but I want to get your take on how things should be done before I get too far into it.

**Comment by benjamin-hodgson** [comment]
I agree with what you say in point 1.

Regarding point 2, a little extra knowledge off the top of my head might help. Each channel (including the connection, which is defined by AMQP to be channel 0) is essentially an _actor_ with an inbox of frames from the server. The channel autonomously pulls frames out of the inbox and processes them using the correct method in the [`Handler`](https://github.com/benjamin-hodgson/asynqp/blob/2b3f32c13d62c5bfe9e579d8835a10cefd3c4dfa/src/asynqp/channel.py#L185). The `Handler` is basically the entry point for a channel to process a frame.

The inbox is implemented as a `Queue` - there is one queue per open channel; these are managed by the [`Dispatcher`](https://github.com/benjamin-hodgson/asynqp/blob/f59a6ec158ac068c9c49cc1b9422266eaad03b15/src/asynqp/routing.py#L10). So when a frame arrives, [the `Protocol` tells the `Dispatcher`](https://github.com/benjamin-hodgson/asynqp/blob/f59a6ec158ac068c9c49cc1b9422266eaad03b15/src/asynqp/protocol.py#L32) to put the frame in the queue of the correct channel.

The `Synchroniser` is basically an implementation detail of the handler; it keeps track of which objects on a channel are waiting for which frames and notifies them when a frame arrives. It mediates between API classes such as `Queue` and the objects which respond to the server (the `Handler`s).

So given all that, I think that error handling should respect the current architecture and go via the `Dispatcher` and the `Handler`. I think the right way to go is to add a special type of message which kills the actor (this is usually called a "poison pill") and a corresponding method on the `Handler` to respond to it. I guess this method would tell its `Synchroniser` to kill all of its currently-live `Futures`.

That sounds like quite a lot of work to me. If you want to submit a pull request for part 1 (raising exceptions from the `Protocol` when the connection dies) and leave part 2 (the poison pill message) to me then I'm fine with that. But if you fancy a challenge then I'll be very happy to accept a contribution for each of them!

**Comment by lenzenmi** [comment]
I missed the ```Handler```. Since it's in communication with the Syncroniser already, a poison pill sounds like a much better approach than collecting references to the Syncronisers directly.

I'm a bit busy with work just now to work on either, but I'd like to help. Depending how things go I may have a chance to look at this next week.

**Comment by benjamin-hodgson** [comment]
:+1:

**Comment by lenzenmi** [comment]
I submitted two pull requests today. The first contains the asynqp to the code and tests, the second contains an example program that automatically reconnects.

**Comment by lenzenmi** [comment]
Meh, failed flake8, those pesky empty spaces on blank lines.

I'll fix and submit new merge requests

**Comment by lenzenmi** [comment]
Yup, builds passing now.

**Comment by benjamin-hodgson** [comment]
Closed by #19
