### ISSUE TITLE
Refactor QueueReader to use single async task

### ISSUE THREAD

**Issue by TarasLevelUp** [benjamin-hodgson/asynqp#44]
Currently the queue reader has next method:
```python
    def ready(self):
        assert not self.is_waiting, "ready() got called while waiting for a frame to be read"
        self.is_waiting = True

        t = asyncio.async(self._read_next(), loop=self._loop)
        if _TEST:  # this feels hacky to me
            t._log_destroy_pending = False
```
If can be rewritten to only contain 1 task, that will always wait for new data and push it to queue.

**Comment by TarasLevelUp** [comment]
Just as a reminder =)

**Comment by TarasLevelUp** [comment]
@benjamin-hodgson 
Cracked my header around 1 element in the library: `reader.ready()`. It basically states, that the reader can process 1 next message. Question: "Why is it necessary to manage this so carefully", or "Will something break if we just pass frames to Actor's the next instant as it arrives (and loop is ticked)"?

**Comment by benjamin-hodgson** [comment]
Your understanding of `ready` is correct.

There are a couple of points tangled up here. The first one is this: `asynqp` is implemented using [the Actor model](https://en.wikipedia.org/wiki/Actor_model). That is, each channel is represented as a single-threaded autonomous component with an inbox of messages from which it reads sequentially, performing actions and updating its internal state as necessary. The input queue of messages is a _central_ part of the Actor model. Without it - if anyone can call any method on any actor at any time - you lose all of the benefits which the Actor model gives you.

The other half of your question is, what is the precise reason I adopted the Actor model at the time that I adopted it? It's because things weren't working properly without it :wink: I previously had a tangle of locks and critical sections which was making the code hard to understand and causing bugs. (The commit messages in 92832c9a343 and 49517bbe117 look related, though I don't really remember the details.)

So, um, don't take it out. However, I do agree that restructuring that `QueueReader` class to explicitly use a looping task is a good idea and would probably improve performance.

**Comment by TarasLevelUp** [comment]
I will look into this for sure. It is better for someone else to give another point of view on the issue.
I think the Actor model works well for this library (If I understood it right, that is =)), so will not do anything too complex.
