### ISSUE TITLE
Question: Is it better than aioamqp ?

### ISSUE THREAD

**Issue by socketpair** [benjamin-hodgson/asynqp#67]
https://github.com/Polyconseil/aioamqp

**Comment by asvetlov** [comment]
@Drizzt1991 maybe you have 5 cents to put in?

**Comment by Drizzt1991** [comment]
Hello. Frankly both aren't good. Few points about both projects:
* `aioamqp` has a bad interface. It resolves purely around callbacks, and it's in the world of asyncio where we have `async for` and `async with` constructs...
* I think `aioamqp` is still a pet project (not that asynqp is better). I didn't contribute to it, but at a slight look can say it's somehow naive in handling things. The methods are not cancellable, socket connections don't actually have proper finalization...
* `asynqp` has potential (at least for me) in the API. It clearly states what's public and how to use things.
* But `asynqp` is not supported. At least no active initiative here. Author does not have time to add features. As for me, I think that asynqp's test suite is Horrible, really it's so hard to add anything, it's killing me. If @benjamin-hodgson would consider to allow changing the test suite I would be happy to keep the project alive, but with current one...
* `asynqp` at the latest released version (0.4) is not usable, the master is ok, but I still use a separate branch in my fork for builds, as I need some features, that benjamin didn't approve.

**Comment by benjamin-hodgson** [comment]
Hello!

I can't speak for `aioamqp`, but @Drizzt1991's assessment of the status of this project is more-or-less accurate. I'm still keeping half an eye on pull requests and issues (hence this message!) but I don't really have the time to keep the library under active development. The bits that exist do work, but I wouldn't consider the library production-ready.

I hear your complaints about the test suite. The framework is quite opinionated, which reflects the way I was thinking about testing at the time that I wrote it. Those opinions aren't wrong but my thinking has mellowed somewhat since then.
That said, the tests themselves aren't bad in my opinion - they are decoupled from the implementation of the library and they offer good code coverage. So I'd be open to helping _translate_ the tests into a more traditional xunit style (I would choose pytest), while keeping the overall structure of the tests intact.

I would like to extend the API to be compatible with Python 3.5's `async/await` constructs. However, it's imperative that we maintain compatibility with Python 3.4.

**Comment by Drizzt1991** [comment]
Sounds great!
How about we make a v0.5 release with the current one and rewrite it for v0.6. Could you create a milestone and mark what should we close for it. I'll be happy to close it.

**Comment by asvetlov** [comment]
+1

On Mon, Feb 29, 2016 at 11:59 AM, Taras Voinarovskyi <
notifications@github.com> wrote:

> Sounds great!
> How about we make a v0.5 release with the current one and rewrite it for
> v0.6. Could you create a milestone and mark what should we close for it.
> I'll be happy to close it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/benjamin-hodgson/asynqp/issues/67#issuecomment-190287951>
> .
>



-- 
Thanks,
Andrew Svetlov

**Comment by benjamin-hodgson** [comment]
Done. You seem keen to get 0.5 out soon so I just labelled bug-fixes. New features and API changes can wait. Let me know if you think I've missed anything. https://github.com/benjamin-hodgson/asynqp/milestones/v0.5

**Comment by dzen** [comment]
Hello @Drizzt1991, thank you for your
