### ISSUE TITLE
"Task was destroyed but is pending!" error in tests

### ISSUE THREAD

**Issue by benjamin-hodgson** [benjamin-hodgson/asynqp#9]
Some - not all - tests print `Task was destroyed but is pending!` for some reason.

This doesn't seem to happen during the integration tests, which suggests that it's a problem with the fixture in the unit tests not tearing itself down properly.

```
$ run-contexts -v test/connection_tests.py:WhenRespondingToConnectionStart
When responding to connection start
  PASS: it should send start ok
----------------------------------------------------------------------
PASSED!
1 context, 1 assertion
(0.0 seconds)
Task was destroyed but it is pending!
task: <Task pending coro=<read_next() running at /Users/ben/Developer/asynqp/src/asynqp/bases.py:48>>
Task was destroyed but it is pending!
task: <Task pending coro=<open_connection() running at /Users/ben/Developer/asynqp/src/asynqp/connection.py:97> wait_for=<Future cancelled>>
```

This might have been due to a Python update; [previous Travis builds](https://travis-ci.org/benjamin-hodgson/asynqp/builds/39942637) don't exhibit this error, but the same code running on my box does.

**Comment by renatomassaro** [comment]
I was having the same issue using a code very similar to the repository example, but making use of `consume` instead of `queue.get()`. I thought this could be the reason but the same error happened with `queue.get()`, so the example on the README has this issue  on `python==3.4.2`.

Closing the channel before closing the connection fixed this for me. I'll submit a PR with the README change.
